
# PCOA

Adapted from Shiv's protocols


```{r}
library(vegan)
```


```{r example eval=FALSE}
normalisedX = sqrt(x) %>% scale(T, T) %>% . - min(.)
bray_grps.D <- vegdist(t(log(ms_data_day12_nonzero))) #calculating distance matrix using bray curtis (default)
res_grps <- pcoa(bray_grps.D)
res_grps$values
PCoA.res<-capscale(bray_grps.D~1,distance="bray") 
```

```{r}
pc<-cmdscale(bray_grps.D, eig=TRUE, add=TRUE, x.ret =TRUE) 
scores_pcoa<-as.data.frame(pc$x)
eig<-eigenvals(pc) 
var_exp<-cumsum(eig)/sum(eig)
var_exp[1:3]

#day4 non zero  cumsum 0.1906465 0.3345288 0.4094569
#day4           cumsum 0.2041412 0.3663344 0.4326650
#day12 non zero cumsum 0.2075193 0.3309860 0.4153886
#day12          cumsum 0.2972361 0.3891566 0.4529161

```

```{r eval=FALSE}
#number of zeroes play a huge role in differentiating between day12 and day12non_zero

#eig/sum(eig)

plot(cumsum(pc$eig) / sum(pc$eig), type="h", lwd=5, las=1,xlab="Number of dimensions",ylab=expression(R^2))
plot(pc$eig, type="h", lwd=5, las=1, xlab="Number of dimensions", ylab="Eigenvalues")

kruskal_pcoa_scores<-sapply(scores_pcoa, function(x) kruskal.test(x~ as.factor(RunDay)) )
aov_pcoa_scores<-sapply(scores_pcoa, function(x) aov(x~ as.factor(RunDay)) )

lm_pcoa_scores<-sapply(scores_pcoa, function(x) 
{
  lm_val<-lm(x~ as.factor(RunDay[24:268])) 
  lm_cor<-summary(lm_val)
  return(lm_cor$r.squared)
})
```

```{r eval=FALSE}
 ## for day 4
 bray_grps.D_day4 <- vegdist(t(log(ms_data_day4)), "bray") #calculating distance matrix using bray curtis
 pc_day4<-cmdscale(bray_grps.D_day4, eig=TRUE, add=TRUE, x.ret =TRUE) 
 scores_pcoa_day4<-as.data.frame(pc_day4$x)
 eig<-eigenvals(pc_day4)
 cumsum(eig/sum(eig))
 kruskal_pcoa_scores_day4<-sapply(scores_pcoa_day4, function(x) kruskal.test(x~ as.factor(RunDay_day4)) )
 aov_pcoa_scores_day4<-sapply(scores_pcoa_day4, function(x) aov(x~ as.factor(RunDay_day4)) )

 cor_pcoa_scores_day4<-sapply(scores_pcoa_day4, function(x) cor.test(x,RunDay_day4,method="kendall",use="all.obs"))

 lm_pcoa_scores_day4<-sapply(scores_pcoa_day4, function(x) 
 {
   lm_val<-lm(x~ as.factor(RunDay_day4)) 
   lm_cor<-summary(lm_val)
   return(lm_cor$r.squared)
 })

 ## for day 12
 bray_grps.D_day12 <- vegdist(t(log(ms_data_day12)), "bray") #calculating distance matrix using bray curtis
 pc_day12<-cmdscale(bray_grps.D_day12, eig=TRUE, add=TRUE, x.ret =TRUE) 
 scores_pcoa_day12<-as.data.frame(pc_day12$x)
 eig<-eigenvals(pc_day12)
 cumsum(eig/sum(eig))
 kruskal_pcoa_scores_day12<-sapply(scores_pcoa_day12, function(x) kruskal.test(x~ as.factor(RunDay_day12)) )
 aov_pcoa_scores_day12<-sapply(scores_pcoa_day12, function(x) aov(x~ as.factor(RunDay_day12)) )
 cor_pcoa_scores_day12<-sapply(scores_pcoa_day12, function(x) cor.test(x,RunDay_day12,method="kendall",use="all.obs"))

 lm_pcoa_scores_day12<-sapply(scores_pcoa_day12, function(x) 
 {
   lm_val<-lm(x~ as.factor(RunDay_day12)) 
   lm_cor<-summary(lm_val)
   return(lm_cor$r.squared)
 })

 # pdf(file="PCOA_samples.pdf")
 # biplot(res_grps)
 # dev.off()

 # Create ordination plot
 # pdf(file="PCOA_ordplot_zeroCor_rem5rep.pdf",width=12, height=12, paper="a4r")
 # fig<-ordiplot(scores(pc)[,c(1,2)], type="t", main="PCoA Samples",cex=0.5)
 # dev.off()
 
 x11()
 ordiplot (scores(pc)[,c(1,2)], display = 'sp', type = 'n',main="PCoA Samples", cex=0.5)
 points(scores(pc)[,c(1,2)], col = clusMember , pch = clusMember )
 legend("bottomleft", legend = c("Day4","Day12"), pch = 1:2,col = c("blue","red"))
```
